use_frameworks!

target 'BMPlayer_Example', :exclusive => true do
  pod 'BMPlayer', :path => '../'
  pod 'SnapKit' , '~> 0.20.0'
end

target 'BMPlayer_Tests', :exclusive => true do
  pod 'BMPlayer', :path => '../'

  
end
